
name: Simple_action

on:
  push:
    branches: [ "main" ]

jobs:
  cat_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cat file.txt
        run: cat file.txt
